name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    strategy:
      matrix:
        ruby:
          - '3.2.1'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Rspec
      run: bundle exec rspec
    - name: Sorbet
      run: bundle exec srb tc
    - name: Rubocop
      run: bundle exec rubocop
